[package]
publish = false
name = "hello_world"
version = "0.1.0"
authors = ["Jannis R <mail@jannisr.de>"]
workspace = "../.."

[dependencies]

[target.asmjs-unknown-emscripten]
rustflags = [
    "-Clink-args=-s EXPORTED_FUNCTIONS=['_say_hello']",
]
